defaults:
  - _self_
  - task: square_image
name: train_robomimic_image

_target_: diffusion_policy.workspace.train_robomimic_image_workspace.TrainRobomimicUniPertImageWorkspaceRNN
algo_name: 'BC_RNN'
checkpoints:
    train0: '/pre_trained_checkpoints/square_image/BC_RNN/train_0/checkpoints/epoch=1400-test_mean_score=0.864.ckpt'

checkpoint: ${checkpoints.train0}
epsilon: 0.0625
epsilon_step: 0.01
task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "FinalRun1_UAP-BC-RNN-pretrainedTrain0-seed0"

view: "both"  # robomimic task

clip_min: 0
clip_max: 1
horizon: &horizon 1
n_obs_steps: 1
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: *horizon
past_action_visible: False
keypoint_visible_rate: 1.0
targeted: False
perturbations: [0.15, 0.15, 0, 0, 0, 0, 0]
log: True
save_video: False
n_vis: 3

patch_path: '/pre_trained_checkpoints/square_image/BC_RNN/train_0/checkpoints/epoch=1400-test_mean_score=0.864.ckpt'

policy:
  _target_: diffusion_policy.policy.robomimic_image_policy.RobomimicImagePolicy
  shape_meta: ${shape_meta}
  algo_name: bc_rnn
  obs_type: image
  # oc.select resolver: key, default
  task_name: ${oc.select:task.task_name,square}
  dataset_type: ${oc.select:task.dataset_type,ph}
  crop_shape: [76,76]


dataloader:
  batch_size: 512
  num_workers: 10
  shuffle: True
  pin_memory: True
  persistent_workers: False
val_dataloader:
  batch_size: 64
  num_workers: 10
  shuffle: False
  pin_memory: True
  persistent_workers: False

training:
  device: "cuda:0"
  seed: 0
  debug: False
  resume: True
  # optimization
  num_epochs: 50
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 25
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: Final_BC_UAP
  mode: online
  name: ${task_name}_${exp_name}_${epsilon}_${targeted}_${view}_${now:%Y.%m.%d}_${now:%H.%M.%S}
  tags: ["${algo_name}", "${task_name}", "${epsilon}","${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: uap_training_runs/${algo_name}_${task_name}/attack_strength_${epsilon}/${exp_name}_${now:%Y.%m.%d}_${now:%H.%M.%S}
  sweep:
    dir:  uap_training_runs/${algo_name}_${task_name}/attack_strength_${epsilon}/${exp_name}_${now:%Y.%m.%d}_${now:%H.%M.%S}
    subdir: ${hydra.job.num}